proxy:
  service:
    type: LoadBalancer
    http:
      port: 8080

singleuser:
  profileList:
    - display_name: "CPU Server"
      description: "Small CPU instance"
      kubespawner_override:
        cpu_limit: 1
        mem_limit: 2G
    - display_name: "GPU Server"
      description: "GPU-enabled instance"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: 1
