apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://hub.jupyter.org/helm-chart/
      chart: jupyterhub
      targetRevision: 4.2.0
      helm:
        valueFiles:
          - $values/values/jupyterhub-values.yaml
    - repoURL: https://github.com/truatlas/argocd-test.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
